"""empty message

Revision ID: 13fa403cdf99
Revises: 67ed10db58d4
Create Date: 2021-03-18 14:40:41.814233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fa403cdf99'
down_revision = '67ed10db58d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('time', sa.String(length=10), nullable=True))
    op.drop_column('activity', 'hour')
    op.drop_column('activity', 'hourdsda')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('hourdsda', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('activity', sa.Column('hour', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('activity', 'time')
    # ### end Alembic commands ###
